services:
  nginx-proxy:
    image: "${DOCKER_DOMAIN}/mixtapestudy/nginx:latest"
    environment:
      - FLASK_SERVER_ADDR=mixtapestudy:8000
    ports:
      - "80:80"
    depends_on:
      - mixtapestudy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1"]
      interval: 2s
      timeout: 10s
      retries: 3
  alembic:
    image: "${DOCKER_DOMAIN}/mixtapestudy/mixtapestudy:latest"
    command: ["alembic", "upgrade", "head"]
    environment:
      DATABASE_URL: "${ADMIN_DATABASE_URL}"
  migration_done:
    # Dummy image for commands to be sure migration is complete
    image: alpine
    command: ["date"]
    depends_on:
      alembic:
        condition: service_completed_successfully
  mixtapestudy:
    image: "${DOCKER_DOMAIN}/mixtapestudy/mixtapestudy:latest"
    ports:
      - "8000:8000"
    environment:
      OAUTH_REDIRECT_BASE_URL: "https://beta.mixtapestudy.com"
      # Set these in a .env file
      SPOTIFY_CLIENT_SECRET: "${SPOTIFY_CLIENT_SECRET}"
      SPOTIFY_CLIENT_ID: "${SPOTIFY_CLIENT_ID}"
      SESSION_SECRET: "${SESSION_SECRET}"
      DATABASE_URL: "${DATABASE_URL}"
      SENTRY_DSN: "${SENTRY_DSN}"
    user: '1001'
    volumes:
      - /opt/mixtapestudy/log:/home/app/log
    depends_on:
      migration_done:
        condition: service_completed_successfully
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8000/flask-health-check || exit 1"]
      interval: 2s
      timeout: 10s
      retries: 3
